name: Deploy to Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Build
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test
  prepare-environment:
        runs-on: self-hosted
        needs: test
        steps:
          - name: Stop and remove containers, networks
            run: docker-compose down
          - name: Remove unused data
            run: docker system prune -a -f
  deploy:
        runs-on: self-hosted
        needs: prepare-environment
        steps:
          - name: checkout repo
            uses: actions/checkout@v3
          - name: docker-compose
            run: docker-compose up -d